version: '3.8'
services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  gateway:
    build: ./gateway
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - sample_backend
    networks:
      - api_security_net

  sample_backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - api_security_net

  # processor:
  #   build: ./processor
  #   environment:
  #     - REDIS_ADDR=redis:6379
  #   depends_on:
  #     - redis
  #   networks:
  #     - api_security_net

networks:
  api_security_net:
    driver: bridge
