services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - api_security_net

  gateway:
    build: ./gateway
    env_file:
      - ./gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      sample_backend:
        condition: service_started
    networks:
      - api_security_net

  sample_backend:
    build: ./sample_backend
    ports:
      - "3000:3000"
    networks:
      - api_security_net

  # processor:
  #   build: ./processor
  #   environment:
  #     - REDIS_ADDR=redis:6379
  #   depends_on:
  #     - redis
  #   networks:
  #     - api_security_net

networks:
  api_security_net:
    driver: bridge
